package com.telcobright.seed.routing.store;

import com.telcobright.seed.routing.policy.PolicyConflictException;
import com.telcobright.seed.routing.policy.RoutingPolicy;
import com.telcobright.seed.routing.spi.PolicyStore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

/**
 * Routing policies in a relational database — ONE table, a few plain columns an index can use, and ONE JSON
 * column ({@code policy_json}: PostgreSQL {@code jsonb}, MySQL {@code json}) that holds the policy's document.
 * Every save keeps the old document in {@code <table>_history}. The store creates its own tables when asked
 * ({@link #ensureSchema}) — idempotent, so a service start may always call it.
 *
 * <pre>
 *   routing_policy(id, domain, name, type, enabled, version, description, policy_json, updated_at, updated_by)
 *                  UNIQUE (domain, name)
 *   routing_policy_history(id, domain, name, version, type, enabled, description, policy_json,
 *                          change_kind, changed_at, changed_by)
 * </pre>
 *
 * The data source is the host's (its pool, its credentials from its secret store) — this class never opens one.
 */
public final class JdbcPolicyStore implements PolicyStore {
    private static final Logger log = LoggerFactory.getLogger(JdbcPolicyStore.class);

    public enum Dialect {
        POSTGRES, MYSQL, GENERIC;

        public static Dialect of(String productName) {
            String p = productName == null ? "" : productName.toLowerCase(Locale.ROOT);
            if (p.contains("postgres")) return POSTGRES;
            if (p.contains("mysql") || p.contains("mariadb")) return MYSQL;
            return GENERIC;
        }
    }

    private final DataSource ds;
    private final Dialect dialect;
    private final String table;
    private final String historyTable;

    public JdbcPolicyStore(DataSource ds) { this(ds, detect(ds), "routing_policy"); }

    public JdbcPolicyStore(DataSource ds, Dialect dialect, String table) {
        if (table == null || !table.matches("[A-Za-z_][A-Za-z0-9_.]{0,62}")) throw new IllegalArgumentException("not a table name: " + table);
        this.ds = ds;
        this.dialect = dialect;
        this.table = table;
        this.historyTable = table + "_history";
    }

    public static Dialect detect(DataSource ds) {
        try (Connection c = ds.getConnection()) {
            return Dialect.of(c.getMetaData().getDatabaseProductName());
        } catch (SQLException e) {
            throw new PolicyStoreException("the policy database cannot be reached to read its kind", e);
        }
    }

    public Dialect dialect() { return dialect; }

    /** Create the two tables when they are not there. Safe on every start. */
    public JdbcPolicyStore ensureSchema() {
        String json = switch (dialect) { case POSTGRES -> "JSONB"; case MYSQL -> "JSON"; case GENERIC -> "VARCHAR(1000000)"; };
        String id = switch (dialect) {
            case POSTGRES -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            case MYSQL -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case GENERIC -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
        };
        String ts = switch (dialect) { case POSTGRES -> "TIMESTAMPTZ"; case MYSQL -> "TIMESTAMP(3)"; case GENERIC -> "TIMESTAMP"; };
        String bool = dialect == Dialect.MYSQL ? "TINYINT(1)" : "BOOLEAN";
        String one = dialect == Dialect.MYSQL ? "1" : "TRUE";
        List<String> ddl = new ArrayList<>();
        ddl.add("CREATE TABLE IF NOT EXISTS " + table + " ("
            + "id " + id + ", domain VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, type VARCHAR(64) NOT NULL, "
            + "enabled " + bool + " DEFAULT " + one + " NOT NULL, version INTEGER DEFAULT 1 NOT NULL, description VARCHAR(512), "
            + "policy_json " + json + " NOT NULL, updated_at " + ts + " NOT NULL, updated_by VARCHAR(128), "
            + "CONSTRAINT " + plain(table) + "_domain_name UNIQUE (domain, name))");
        ddl.add("CREATE TABLE IF NOT EXISTS " + historyTable + " ("
            + "id " + id + ", domain VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, version INTEGER NOT NULL, type VARCHAR(64) NOT NULL, "
            + "enabled " + bool + " NOT NULL, description VARCHAR(512), policy_json " + json + " NOT NULL, "
            + changeColumn() + " VARCHAR(16) NOT NULL, changed_at " + ts + " NOT NULL, changed_by VARCHAR(128))");
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            for (String sql : ddl) st.execute(sql);
            if (dialect != Dialect.MYSQL) {
                st.execute("CREATE INDEX IF NOT EXISTS " + plain(historyTable) + "_key ON " + historyTable + " (domain, name, version)");
            } else if (!mysqlIndexExists(c, historyTable, plain(historyTable) + "_key")) {
                st.execute("CREATE INDEX " + plain(historyTable) + "_key ON " + historyTable + " (domain, name, version)");
            }
        } catch (SQLException e) {
            throw new PolicyStoreException("the routing policy tables could not be created in " + table, e);
        }
        log.info("routing policy store ready: table {} ({})", table, dialect);
        return this;
    }

    /** {@code change} is a reserved word in MySQL: the history column is {@code change_kind} everywhere. */
    private static String changeColumn() { return "change_kind"; }

    private static boolean mysqlIndexExists(Connection c, String table, String index) throws SQLException {
        try (ResultSet rs = c.getMetaData().getIndexInfo(c.getCatalog(), null, table, false, false)) {
            while (rs.next()) if (index.equalsIgnoreCase(rs.getString("INDEX_NAME"))) return true;
        }
        return false;
    }

    private static String plain(String t) { return t.replace('.', '_'); }

    private String jsonParam() {
        return switch (dialect) { case POSTGRES -> "CAST(? AS JSONB)"; case MYSQL -> "CAST(? AS JSON)"; case GENERIC -> "?"; };
    }

    private static final String COLUMNS = "domain, name, type, enabled, version, description, policy_json, updated_at, updated_by";

    @Override
    public Optional<RoutingPolicy> find(String domain, String name) {
        String sql = "SELECT " + COLUMNS + " FROM " + table + " WHERE domain = ? AND name = ?";
        try (Connection c = ds.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, norm(domain));
            ps.setString(2, norm(name));
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(row(rs)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new PolicyStoreException("policy " + domain + "/" + name + " could not be read", e);
        }
    }

    @Override
    public List<RoutingPolicy> list(String domain) {
        boolean all = domain == null || domain.isBlank();
        String sql = "SELECT " + COLUMNS + " FROM " + table + (all ? "" : " WHERE domain = ?") + " ORDER BY domain, name";
        try (Connection c = ds.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            if (!all) ps.setString(1, norm(domain));
            List<RoutingPolicy> out = new ArrayList<>();
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) out.add(row(rs));
            }
            return out;
        } catch (SQLException e) {
            throw new PolicyStoreException("the routing policies could not be listed", e);
        }
    }

    @Override
    public RoutingPolicy save(RoutingPolicy policy, String by) {
        PolicyNames.check(policy);
        RoutingPolicy p = PolicyNames.normalised(policy);
        Instant now = Instant.now();
        try (Connection c = ds.getConnection()) {
            boolean auto = c.getAutoCommit();
            c.setAutoCommit(false);
            try {
                int newVersion;
                if (p.version() == 0) {
                    Integer stored = storedVersion(c, p);
                    if (stored != null) throw new PolicyConflictException("policy '" + p.name() + "' of " + p.domain() + " exists already (version " + stored + ")", stored);
                    newVersion = 1;
                    String sql = "INSERT INTO " + table + " (" + COLUMNS + ") VALUES (?, ?, ?, ?, ?, ?, " + jsonParam() + ", ?, ?)";
                    try (PreparedStatement ps = c.prepareStatement(sql)) {
                        ps.setString(1, p.domain());
                        ps.setString(2, p.name());
                        ps.setString(3, p.type());
                        ps.setBoolean(4, p.enabled());
                        ps.setInt(5, newVersion);
                        ps.setString(6, p.description());
                        ps.setString(7, p.document());
                        ps.setTimestamp(8, Timestamp.from(now));
                        ps.setString(9, by);
                        ps.executeUpdate();
                    }
                } else {
                    newVersion = p.version() + 1;
                    String sql = "UPDATE " + table + " SET type = ?, enabled = ?, version = ?, description = ?, policy_json = " + jsonParam()
                        + ", updated_at = ?, updated_by = ? WHERE domain = ? AND name = ? AND version = ?";
                    int n;
                    try (PreparedStatement ps = c.prepareStatement(sql)) {
                        ps.setString(1, p.type());
                        ps.setBoolean(2, p.enabled());
                        ps.setInt(3, newVersion);
                        ps.setString(4, p.description());
                        ps.setString(5, p.document());
                        ps.setTimestamp(6, Timestamp.from(now));
                        ps.setString(7, by);
                        ps.setString(8, p.domain());
                        ps.setString(9, p.name());
                        ps.setInt(10, p.version());
                        n = ps.executeUpdate();
                    }
                    if (n == 0) {
                        Integer stored = storedVersion(c, p);
                        throw new PolicyConflictException("policy '" + p.name() + "' was changed by someone else: you edited version " + p.version()
                            + ", the store holds " + (stored == null ? "none" : "version " + stored), stored == null ? 0 : stored);
                    }
                }
                RoutingPolicy saved = p.withVersion(newVersion, now, by);
                remember(c, saved, p.version() == 0 ? "created" : "updated", now, by);
                c.commit();
                return saved;
            } catch (SQLException | RuntimeException e) {
                c.rollback();
                throw e;
            } finally {
                c.setAutoCommit(auto);
            }
        } catch (SQLException e) {
            if (isDuplicate(e)) throw new PolicyConflictException("policy '" + p.name() + "' of " + p.domain() + " was created by someone else just now", 1);
            throw new PolicyStoreException("policy " + p.key() + " could not be saved", e);
        }
    }

    private Integer storedVersion(Connection c, RoutingPolicy p) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement("SELECT version FROM " + table + " WHERE domain = ? AND name = ?")) {
            ps.setString(1, p.domain());
            ps.setString(2, p.name());
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getInt(1) : null;
            }
        }
    }

    private void remember(Connection c, RoutingPolicy p, String change, Instant at, String by) throws SQLException {
        String sql = "INSERT INTO " + historyTable + " (domain, name, version, type, enabled, description, policy_json, " + changeColumn()
            + ", changed_at, changed_by) VALUES (?, ?, ?, ?, ?, ?, " + jsonParam() + ", ?, ?, ?)";
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, p.domain());
            ps.setString(2, p.name());
            ps.setInt(3, p.version());
            ps.setString(4, p.type());
            ps.setBoolean(5, p.enabled());
            ps.setString(6, p.description());
            ps.setString(7, p.document());
            ps.setString(8, change);
            ps.setTimestamp(9, Timestamp.from(at));
            ps.setString(10, by);
            ps.executeUpdate();
        }
    }

    @Override
    public boolean delete(String domain, String name, String by) {
        try (Connection c = ds.getConnection()) {
            boolean auto = c.getAutoCommit();
            c.setAutoCommit(false);
            try {
                Optional<RoutingPolicy> stored = findIn(c, domain, name);
                if (stored.isEmpty()) { c.rollback(); return false; }
                Instant now = Instant.now();
                remember(c, stored.get(), "deleted", now, by);
                try (PreparedStatement ps = c.prepareStatement("DELETE FROM " + table + " WHERE domain = ? AND name = ?")) {
                    ps.setString(1, norm(domain));
                    ps.setString(2, norm(name));
                    ps.executeUpdate();
                }
                c.commit();
                return true;
            } catch (SQLException | RuntimeException e) {
                c.rollback();
                throw e;
            } finally {
                c.setAutoCommit(auto);
            }
        } catch (SQLException e) {
            throw new PolicyStoreException("policy " + domain + "/" + name + " could not be deleted", e);
        }
    }

    private Optional<RoutingPolicy> findIn(Connection c, String domain, String name) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement("SELECT " + COLUMNS + " FROM " + table + " WHERE domain = ? AND name = ?")) {
            ps.setString(1, norm(domain));
            ps.setString(2, norm(name));
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(row(rs)) : Optional.empty();
            }
        }
    }

    @Override
    public List<RoutingPolicy> history(String domain, String name, int limit) {
        String sql = "SELECT domain, name, type, enabled, version, description, policy_json, changed_at AS updated_at, changed_by AS updated_by FROM "
            + historyTable + " WHERE domain = ? AND name = ? ORDER BY id DESC LIMIT ?";
        try (Connection c = ds.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, norm(domain));
            ps.setString(2, norm(name));
            ps.setInt(3, Math.max(1, limit));
            List<RoutingPolicy> out = new ArrayList<>();
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) out.add(row(rs));
            }
            return out;
        } catch (SQLException e) {
            throw new PolicyStoreException("the history of policy " + domain + "/" + name + " could not be read", e);
        }
    }

    @Override
    public String fingerprint() {
        String sql = "SELECT COUNT(*), COALESCE(SUM(version), 0), MAX(updated_at) FROM " + table;
        try (Connection c = ds.getConnection(); Statement st = c.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            rs.next();
            Timestamp last = rs.getTimestamp(3);
            return rs.getLong(1) + ":" + rs.getLong(2) + ":" + (last == null ? 0 : last.getTime());
        } catch (SQLException e) {
            throw new PolicyStoreException("the routing policy table could not be read", e);
        }
    }

    private static RoutingPolicy row(ResultSet rs) throws SQLException {
        Timestamp at = rs.getTimestamp("updated_at");
        return new RoutingPolicy(rs.getString("domain"), rs.getString("name"), rs.getString("type"), rs.getBoolean("enabled"),
            rs.getInt("version"), rs.getString("description"), rs.getString("policy_json"), at == null ? null : at.toInstant(),
            rs.getString("updated_by"));
    }

    private static boolean isDuplicate(SQLException e) {
        String state = e.getSQLState();
        return state != null && state.startsWith("23");
    }

    private static String norm(String s) { return s == null ? "" : s.trim().toLowerCase(Locale.ROOT); }
}
